In [1]:
import numpy as np
mydata = np.arange(0,20)
print(mydata)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [2]:
# Reshape into a matrix
# Pass in tuple(rows,columns)
# NOTE: default is opposite to R (in R would be populated downwards, column-wise)
np.reshape(mydata, (5,4))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [3]:
# Same result as above
# Confirms that the default when you don't specify parameter is 'C' like behavior
np.reshape(mydata, (5,4), order = 'C')

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [4]:
MATR1 = np.reshape(mydata, (5,4), order = 'C')
MATR1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [5]:
# Exercise - get to the number 10:
MATR1[2,2]

10

In [6]:
# Fortran like behavior 
MATR2 = np.reshape(mydata, (5,4), order = 'F')
MATR2

array([[ 0,  5, 10, 15],
       [ 1,  6, 11, 16],
       [ 2,  7, 12, 17],
       [ 3,  8, 13, 18],
       [ 4,  9, 14, 19]])

In [7]:
# Exercise - get to the number 10:
MATR2[0,2]

10

In [11]:
# OOP Concept: 
# One way to find the function reshape() is to go to the package
# Then pass it the list/data we're working with and dimensions 
# np.reshape(mydata, (5,4))

# But mydata is not just a list, it is an array 
# Because it was created with the arrange function 
# That means mydata is an object that already contains the reshape() function 
# So can apply/call the function from within the object itself and just pass the dimensions
# Don't have to go into numpy package and find the function

# Benefit of OOP is that these objects carry around not only data
# But also the functions within themselves

# Get the same result 
mydata.reshape((5,4))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [12]:
# -----------------------------

In [13]:
r1 =  ["I", "am", "happy"]
r2 = ["What", "a", "day"]
r3 = [1, 2, 3]

In [14]:
[r1, r2, r3]

[['I', 'am', 'happy'], ['What', 'a', 'day'], [1, 2, 3]]

In [16]:
# Combine lists into a matrix row-by-row (each list is its own row)
# Tells you the type of data in the matrix
# "<U5" means less than 5 unicode characters in the strings
# Each of the elements are turned into a string
# Because in arrays, can only have one type of data 
# Easier to convert number into a string
np.array([r1, r2, r3])

array([['I', 'am', 'happy'],
       ['What', 'a', 'day'],
       ['1', '2', '3']],
      dtype='<U5')

In [18]:
# Don't display dtype
print(np.array([r1, r2, r3]))

[['I' 'am' 'happy']
 ['What' 'a' 'day']
 ['1' '2' '3']]


In [19]:
# ------------------------------------

In [20]:
# Dictionaries
# Like a list, difference is a list is an ordered set of elements 
# Dictionary is not ordered, it has a key
dict1 = {'key1':'val1','key2':'val2','key3':'val3'}

In [21]:
# Therefore, elements are accessed by key in a dictionary
# In a list, it would be accessed by index number 
dict1['key2']

'val2'

In [22]:
dict1['key1']

'val1'

In [23]:
dict1

{'key1': 'val1', 'key2': 'val2', 'key3': 'val3'}

In [24]:
# Dictionaries can have different data types just like lists 
dict2 = {'Germany':'I have been here', 'France':2, 'Spain':True}

In [25]:
# Notice that order is not the same 
# In dictionaries, order don't matter at all 
# You can only access elements through the keys anyway
# So it is stored however is most efficient for Python
# It doesn't maintain the order in which you specified them 
dict2

{'France': 2, 'Germany': 'I have been here', 'Spain': True}

In [26]:
dict2['France']

2

In [27]:
# --------------------------------

In [28]:
# Matrix Operations 

# Surpress warnings
import warnings
warnings.filterwarnings('ignore')

# Divide matrix
# np.matrix.round(Matrix1/Matrix2)
FieldGoalsPerGame = np.matrix.round(FieldGoals/Games)
np.matrix.round(MinutesPlayed/Games) 

In [29]:
# --------------------------------

In [30]:
# Visualization 

In [31]:
import numpy as np

# matplotlib comes part of Anaconda distribution
import matplotlib.pyplot as plt 

# To put plots in the actual Jupyter notebook instead of separate window
# Only need to do this once 
%matplotlib inline

# Set parameters for session
plt.rcParams['figure.figsize'] = 8,4

# Basic plot of salary matrix
plt.plot(Salary[0], c= 'Black',ls = '--', marker = 's', ms = 7, label = Players[0])

# Want season on x-axis not the number
plt.xticks(list(range(0,9)), Seasons, rotation = 'vertical')

# Displaying the plot instead of just sending the object to the output 
# Like print() 
plt.show()

In [33]:
# More Visualization

In [ ]:
# Line styles: https://matplotlib.org/stable/gallery/lines_bars_and_markers/linestyles.html
# Markers: https://matplotlib.org/stable/api/markers_api.html
plt.plot(Salary[0], c= 'Black',ls = '--', marker = 's', ms = 7, label = Players[0])

# Add rows (players) from the matrix 
plt.plot(Salary[1], c= 'Red',ls = '--', marker = 'o', ms = 7, label = Players[1])
plt.plot(Salary[2], c= 'Green',ls = '--', marker = '^', ms = 7, label = Players[2])
plt.plot(Salary[3], c= 'Blue',ls = '--', marker = 'D', ms = 7, label = Players[3])
plt.plot(Salary[4], c= 'Pink',ls = '--', marker = 's', ms = 7, label = Players[4])


plt.plot(Salary[5], c= 'Black',ls = '--', marker = 'o', ms = 7, label = Players[5])
plt.plot(Salary[6], c= 'Red',ls = '--', marker = '^', ms = 7, label = Players[6])
plt.plot(Salary[7], c= 'Green',ls = '--', marker = 'D', ms = 7, label = Players[7])
plt.plot(Salary[8], c= 'Blue',ls = '--', marker = 's', ms = 7, label = Players[8])
plt.plot(Salary[9], c= 'Pink',ls = '--', marker = 'o', ms = 7, label = Players[9])


# Add legend and where you what to lock it in 
# 'upper left' means you want the upper left corner of the legend to be touching the axis
# bb_to_anchor means I  want N "length"/side of the legend on  the x axis
# and N length/side of the legend on the y-axis

plt.legend(loc = 'upper left', bbox_to_anchor = (1,1)) 

plt.xticks(list(range(0,9)), Seasons, rotation = 'vertical')
plt.show()

In [ ]:
# Replace matrix with Games matrix
plt.plot(Games[0], c= 'Black',ls = '--', marker = 's', ms = 7, label = Players[0])
plt.plot(Games[1], c= 'Red',ls = '--', marker = 'o', ms = 7, label = Players[1])
plt.plot(Games[2], c= 'Green',ls = '--', marker = '^', ms = 7, label = Players[2])
plt.plot(Games[3], c= 'Blue',ls = '--', marker = 'D', ms = 7, label = Players[3])
plt.plot(Games[4], c= 'Pink',ls = '--', marker = 's', ms = 7, label = Players[4])
plt.plot(Games[5], c= 'Black',ls = '--', marker = 'o', ms = 7, label = Players[5])
plt.plot(Games[6], c= 'Red',ls = '--', marker = '^', ms = 7, label = Players[6])
plt.plot(Games[7], c= 'Green',ls = '--', marker = 'D', ms = 7, label = Players[7])
plt.plot(Games[8], c= 'Blue',ls = '--', marker = 's', ms = 7, label = Players[8])
plt.plot(Games[9], c= 'Pink',ls = '--', marker = 'o', ms = 7, label = Players[9])
plt.legend(loc = 'upper left', bbox_to_anchor = (1,1)) 
plt.xticks(list(range(0,9)), Seasons, rotation = 'vertical')
plt.show()

In [34]:
# Our Own Function 

In [ ]:
def myplot(playerlist):
    for name in playerlist:
        plt.plot(Games[Pdict[name]], c= 'Black',ls = '--', marker = 's', ms = 7, label = name)
    plt.legend(loc = 'upper left', bbox_to_anchor = (1,1)) 
    plt.xticks(list(range(0,9)), Seasons, rotation = 'vertical')
    plt.show()

In [ ]:
# Pass in playerlist to plot 
myplot(['PlayerName1','PlayerName2','PlayerName3'])

In [ ]:
# Advanced Function Design
# Assign different colors and markers to different players

def myplot(playerlist):
    Col = {"PlayerName1":"Black", "PlayerName2":"Blue",...}
    Mrk = {"PlayerName1":"s", "PlayerName2":"o",...}
    for name in playerlist:
        plt.plot(Games[Pdict[name]], c = Col[name],ls = '--', marker = Mrk[name], ms = 7, label = name)
    plt.legend(loc = 'upper left', bbox_to_anchor = (1,1)) 
    plt.xticks(list(range(0,9)), Seasons, rotation = 'vertical')
    plt.show()

# Pass in playerlist to plot 
myplot(['PlayerName1','PlayerName2','PlayerName3'])

In [ ]:
# Fix up the inputs 
# Specify which matrix you want pull data from 
def myplot(data, playerlist = Players): # specify default value as all players
    Col = {"PlayerName1":"Black", "PlayerName2":"Blue",...}
    Mrk = {"PlayerName1":"s", "PlayerName2":"o",...}
    for name in playerlist:
        plt.plot(data[Pdict[name]], c = Col[name],ls = '--', marker = Mrk[name], ms = 7, label = name)
    plt.legend(loc = 'upper left', bbox_to_anchor = (1,1)) 
    plt.xticks(list(range(0,9)), Seasons, rotation = 'vertical')
    plt.show()

# Pass in matrix to pull data from and playerlist to plot 
myplot([Points, 'PlayerName1','PlayerName2','PlayerName3'])

# Plot default value of all the players if playerlist not passed to function
myplot(Salary)

In [ ]:
# Insights
myplot(Games)

In [ ]:
# Salary
myplot(Salary)
myplot(Salary/Games)
myplot(Salary/FieldGoals)

In [ ]:
# In-Game Metrics
myplot(MinutesPlayed)
myplot(Points)

In [ ]:
# In-Game Metrics Normalized (Per Game)
myplot(FieldGoals/Games)
myplot(FieldGoals/FieldGoalAttempts)
myplot(FieldGoalAttempts/Games)
myplot(Points/Games)

In [ ]:
# Interesting Observation
myplot(MinutesPlayed/Games)
myplot(Games)

In [ ]:
# Time is valuable
myplot(FieldGoals/MinutesPlayed)

In [ ]:
# Player Style
myplot(Points/FieldGoals)