___

<a href='http://www.pieriandata.com'> <img src='../Pierian_Data_Logo.png' /></a>
___

# NumPy Indexing and Selection

In this lecture we will discuss how to select elements or groups of elements from an array.

In [1]:
import numpy as np

In [2]:
#Creating sample array
arr = np.arange(0,11)

In [3]:
#Show
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

## Bracket Indexing and Selection
The simplest way to pick one or some elements of an array looks very similar to python lists:

In [4]:
#Get a value at an index
arr[8]

8

In [5]:
# Get values in a range
arr[1:5]

array([1, 2, 3, 4])

In [6]:
#Get values in a range
arr[0:5]

array([0, 1, 2, 3, 4])

In [7]:
# Everything to up an index
arr[:6]

array([0, 1, 2, 3, 4, 5])

In [8]:
# Same as if you put the 0 as the starting index
arr[:6]

array([0, 1, 2, 3, 4, 5])

In [9]:
# Grab everything up to the end the array 
arr[5:]

array([ 5,  6,  7,  8,  9, 10])

## Broadcasting

Numpy arrays differ from a normal Python list because of their ability to broadcast:

In [10]:
#Setting a value with index range (Broadcasting)
# Broadcasts the first 5 values in the array to be 100
arr[0:5]=100

#Show
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [11]:
# Reset array, we'll see why I had to reset in  a moment
arr = np.arange(0,11)

#Show
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [12]:
#Important notes on Slices

# If you grab a slice of an array and set it as a variable 
# Without explicitly saying that you want a copy of the array
slice_of_arr = arr[0:6]

# Show slice
# You're just "viewing" a link to the original array 
slice_of_arr

array([0, 1, 2, 3, 4, 5])

In [13]:
# Change Slice
# Broadcast the slice of an array
slice_of_arr[:]=99

#Show Slice again
slice_of_arr

array([99, 99, 99, 99, 99, 99])

Now note the changes also occur in our original array!

In [14]:
# Any changes you do to the slice will actually affect the original array
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

Data is not copied, it's a view of the original array! This avoids memory problems!

In [15]:
# Numpy does not automatically create copies of an array when you slice 
# If you actually want a copy and not a reference to the original array 
# Have to specifically indicate you want to copy 

#To get a copy, need to be explicit
arr_copy = arr.copy()

arr_copy

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [16]:
# Change the copy 
# Broadcast every value to be 100
arr_copy[:] = 100

In [17]:
# See the changes when you check the copy 
arr_copy

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [18]:
# Original array is unaffected by the broadcast
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

## Indexing a 2D array (matrices)

The general format is **arr_2d[row][col]** or **arr_2d[row,col]**. I recommend usually using the comma notation for clarity.

In [19]:
# Pass in nested list to create 2D array 
arr_2d = np.array(([5,10,15],[20,25,30],[35,40,45]))

# Show
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [20]:
# Index entire row at index 0
arr_2d[0]

array([ 5, 10, 15])

In [21]:
# Can also do this to get entire row
arr_2d[0,:]

array([ 5, 10, 15])

In [22]:
# Entire column at index 0
arr_2d[:,0]

array([ 5, 20, 35])

In [23]:
#Indexing row at index 1
arr_2d[1]

array([20, 25, 30])

In [24]:
############### Single Elements ###############
##### Double Bracket notation arr_2d[row][col] #####
# Grab the value 25 from the matrix 
arr_2d[1][1]

25

In [25]:
# Grab the value 40 from the matrix
arr_2d[2][1]

40

In [26]:
# Double Bracket notation arr_2d[row][col]
arr_2d[0][0]

5

In [27]:
# Format is arr_2d[row][col] or arr_2d[row,col]
# Getting individual element value
arr_2d[1][0]

20

In [28]:
##### Single Bracket notation arr_2d[row,col] #####
# Recommended way, less prone to error  

# Grab the value 40 from the matrix
arr_2d[2,1]

40

In [29]:
# Grab the value 30 from the matrix
arr_2d[1,2]

30

In [30]:
# Same as double brackets version
arr_2d[1][2]

30

In [31]:
# Getting individual element value
arr_2d[1,0]

20

In [32]:
############### Multiple Elements ###############
# Getting chunks of the array 
# Want sub-matrices from the matrix 

# 2D array slicing
# Shape (2,2) from top right corner

# arr_2d[row start:stop, column start: stop]

# Grab everything up to row 2 (but not including)
# Then grab from column 1 onwards
arr_2d[:2, 1:] 

array([[10, 15],
       [25, 30]])

In [33]:
#Shape bottom row
arr_2d[2]

array([35, 40, 45])

In [34]:
#Shape bottom row
arr_2d[2,:]

array([35, 40, 45])

### Fancy Indexing

Fancy indexing allows you to select entire rows or columns out of order,to show this, let's quickly build out a numpy array:

In [35]:
#Set up matrix
arr2d = np.zeros((10,10))

In [36]:
#Length of array
arr_length = arr2d.shape[1]

In [37]:
# Set up array
for i in range(arr_length):
    arr2d[i] = i
    
arr2d

array([[ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.],
       [ 3.,  3.,  3.,  3.,  3.,  3.,  3.,  3.,  3.,  3.],
       [ 4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.],
       [ 5.,  5.,  5.,  5.,  5.,  5.,  5.,  5.,  5.,  5.],
       [ 6.,  6.,  6.,  6.,  6.,  6.,  6.,  6.,  6.,  6.],
       [ 7.,  7.,  7.,  7.,  7.,  7.,  7.,  7.,  7.,  7.],
       [ 8.,  8.,  8.,  8.,  8.,  8.,  8.,  8.,  8.,  8.],
       [ 9.,  9.,  9.,  9.,  9.,  9.,  9.,  9.,  9.,  9.]])

Fancy indexing allows the following

In [38]:
# Entire rows 
arr2d[[2,4,6,8]]

array([[ 2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.],
       [ 4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.],
       [ 6.,  6.,  6.,  6.,  6.,  6.,  6.,  6.,  6.,  6.],
       [ 8.,  8.,  8.,  8.,  8.,  8.,  8.,  8.,  8.,  8.]])

In [39]:
# Allows rows in any order
arr2d[[6,4,2,7]]

array([[ 6.,  6.,  6.,  6.,  6.,  6.,  6.,  6.,  6.,  6.],
       [ 4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.],
       [ 2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.],
       [ 7.,  7.,  7.,  7.,  7.,  7.,  7.,  7.,  7.,  7.]])

In [40]:
# Above is the same as this 
arr2d[[6,4,2,7],:]

array([[ 6.,  6.,  6.,  6.,  6.,  6.,  6.,  6.,  6.,  6.],
       [ 4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.],
       [ 2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.],
       [ 7.,  7.,  7.,  7.,  7.,  7.,  7.,  7.,  7.,  7.]])

In [41]:
# Entire columns in any order 
arr2d[:, [6,4,2,7]]

array([[ 0.,  0.,  0.,  0.],
       [ 1.,  1.,  1.,  1.],
       [ 2.,  2.,  2.,  2.],
       [ 3.,  3.,  3.,  3.],
       [ 4.,  4.,  4.,  4.],
       [ 5.,  5.,  5.,  5.],
       [ 6.,  6.,  6.,  6.],
       [ 7.,  7.,  7.,  7.],
       [ 8.,  8.,  8.,  8.],
       [ 9.,  9.,  9.,  9.]])

## More Indexing Help
Indexing a 2d matrix can be a bit confusing at first, especially when you start to add in step size. Try google image searching NumPy indexing to fins useful images, like this one:

<img src= 'http://memory.osu.edu/classes/python/_images/numpy_indexing.png' width=500/>

## Selection

Let's briefly go over how to use brackets for selection based off of comparison operators.

In [42]:
arr = np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [43]:
# Use comparison operator on an array 
# Will return a Boolean array 
arr > 4

array([False, False, False, False,  True,  True,  True,  True,  True,  True], dtype=bool)

In [44]:
# Save to a variable
bool_arr = arr>4

In [45]:
bool_arr

array([False, False, False, False,  True,  True,  True,  True,  True,  True], dtype=bool)

In [46]:
# Can that Boolean array to conditional selection 
# Pass that the Boolean array in brackets
# To index or conditionally select elements from the original array where the Boolean is True
# Only returns instances where the Boolean array was True
arr[bool_arr]

array([ 5,  6,  7,  8,  9, 10])

In [47]:
# More commonly would do this all in one step 
# Pass in the conditional statement in brackets 
arr[arr>2]

array([ 3,  4,  5,  6,  7,  8,  9, 10])

In [48]:
# All the elements that are less than 3
arr[arr<3]

array([1, 2])

In [49]:
x = 2
arr[arr>x]

array([ 3,  4,  5,  6,  7,  8,  9, 10])

In [50]:
# Practice array
arr_2d = np.arange(50).reshape(5,10)
arr_2d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [51]:
# Use bracket notation to grab chunks 
arr_2d[1:3,3:5]

array([[13, 14],
       [23, 24]])

In [52]:
arr_2d[1:3]

array([[10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

# Great Job!
