In [ ]:
##################  NumPy and Arrays in Python #####################

In [1]:
l = [23245, 27, 546, 215, -1234]

In [2]:
l

[23245, 27, 546, 215, -1234]

In [3]:
import numpy as np 

In [5]:
# Function to convert a list into an array 
a = np.array(l)

In [6]:
a

array([23245,    27,   546,   215, -1234])

In [7]:
b = np.array([12, 455, 63.3, True, "abc"])

In [9]:
# It's an array, but they've all been converted to strings 
# Because there was one string in there already so everything was converted to strings
# Everything has to be the same data type 
print(b)

['12' '455' '63.3' 'True' 'abc']


In [14]:
# Converting a list of integers and booleans
# Will automatically convert like above 
# This time Booleans are converted to integers 
c = np.array([12, 455, 63.3, True])

In [15]:
c


array([  12. ,  455. ,   63.3,    1. ])

In [10]:
# Certain methods are available for list objects 
# Pop out last value of the list
l.pop()

-1234

In [11]:
# List doesn't have that value anymore
l

[23245, 27, 546, 215]

In [12]:
a.mean()

4559.8000000000002

In [ ]:
##################  Slicing Arrays #####################

In [16]:
a

array([23245,    27,   546,   215, -1234])

In [ ]:
# --------- Slicing Lists --------------
# When you slice a list, you create a copy of that list 
# Then work with that slice separately, doesn't change the original list 

In [17]:
l

[23245, 27, 546, 215]

In [18]:
l[1:]

[27, 546, 215]

In [19]:
l[0:2]

[23245, 27]

In [20]:
l[::2]

[23245, 546]

In [21]:
# --------------- Slicing Arrays ---------------

In [22]:
a

array([23245,    27,   546,   215, -1234])

In [23]:
a[2:]

array([  546,   215, -1234])

In [24]:
a[2:4]

array([546, 215])

In [25]:
# When you create a slice of an array, you're NOT creating a new array with that slice
# You're just creating a "view" of that array with the slice
# You're still working with the exact same array
# So if you make changes to the slice you'll make changes to the original array 
# This is how Python/Numpy protects the memory of the computer
# Creating copies of arrays unneccesarily just takes up memory space

In [26]:
# Slicing an array, you've created a view of array a
b = a[2:4]

In [27]:
b

array([546, 215])

In [28]:
b[0]

546

In [30]:
# Make changes to the slice 
b[:] = 111

In [31]:
b

array([111, 111])

In [32]:
# Values will also be replaced in the original array the slice came from 
a

array([23245,    27,   111,   111, -1234])

In [33]:
# Can always call the copy() method to make an actual COPY of the array 
# Tell Numpy yes I want to do this, not using resources by accident 
c = a.copy()

In [35]:
# Now if we change the array 
c[0] = 0

In [37]:
c

array([    0,    27,   111,   111, -1234])

In [38]:
#  Original array that it came from is unaffected
a

In [39]:
a

array([23245,    27,   111,   111, -1234])